added git hooks

diff --git a/git/template.d/hooks/pre-commit b/git/template.d/hooks/pre-commit
--- a/git/template.d/hooks/pre-commit
+++ b/git/template.d/hooks/pre-commit
@@ -1,44 +1,34 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
-
-errood
-errtnp
-errinp
-errvnp
-errsnp
+br="$(git rev-parse --abbrev-ref HEAD)"
 
 die() {
-  printf "${RED}"
-  printf "${1}" "${2}" >&2
-  printf "${RST}"
-
-  printf "info: use '--no-verify' to disable this check"
+  printf "fatal: ${1}\n" "${2}" >&2
+  printf "info: use '--no-verify' to disable this check\n"
 
   exit 1
 }
 
-restore_state() {
-  git checkout ${branch} &>/dev/null
-  git stash apply        &>/dev/null
+verify_up_to_date() {
+  git fetch \
+    && cn="$(git log HEAD..origin/master --oneline | wc -l)"
+
+  [ "${cn}" = "0" ] \
+    || die "branch '${br}' not up to date with master.\
+    \nrun 'git rebase master' and try again\n"
 }
 
-validate_sbt() {
-  sbt test 	  | grep error && die "" ""
-  sbt it:test	  | grep error && die "" ""
-  sbt validate    | grep error && die "" ""
-  sbt scalastyle  | grep error && die "" ""
+verify_branch() {
+  [ "${br}" = "master" ] \
+    && die "cannot commit directly to 'master'\n"
+
+  [[ "${br}" =~ ^BTAT-[0\-9]{4}$ ]] \
+    || die "branch name '${br}' is incorrectly formatted\n"
 }
 
-validate_up_to_date() {
-  git checkout master  
+main() {
+  verify_branch
+  verify_up_to_date
 }
 
-validate_not_master() {
-  [ "${branch}" = "master" ] \
-    && die "" ""
-}
-
-trap restore_state EXIT
-
-
+main
